config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'books#index'
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
validates :name ,presence: true,length: { minimum: 4}
validates :price ,presence: true ,numericality: { greater_than: 0}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController



  def index
    @books = Book.all   
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params) 

    if @book.save
      redirect_to books_path,notice: '新增成功'
    else
      render :new,notice: '新增失敗'
    end

  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
    
  end

  def update
    @book = Book.find(params[:id])
       
    if @book.update(book_params)
      redirect_to books_path,notice: '修改成功'
    else
      render :edit,notice: '修改失敗'
    end 
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path,notice: '刪除成功'
  end

  private

  def book_params
    params.require(:book).permit(:name ,:price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>修改書籍頁面</h1>

<% if @book.errors.any?%>
<ul>
<% @book.errors.full_messages.each do |message|%>
<li><%= message %></li>
<% end %>
</ul>
<% end %>



<%= form_for(@book) do |f| %>
<%= f.label '書籍名稱'%>
<%= f.text_field :name %>
<br>
<%= f.label '書籍價格'%>
<%= f.text_field :price %>
<br>
<%= f.submit '送出'%>
<% end %>

app/views/books/index.html.erb
<h1>SMD book 首頁</h1>
<br>
<%= link_to '新增書籍' , new_book_path %>
<br>
<br>
<ul class="booklist">
<% @books.each do |book| %>
<li>
<%= link_to '編輯', edit_book_path(book.id)%>
<%= link_to '刪除', book_path(book.id),
                   method: :delete,
                   data: {  confirm: '你確定要刪除嗎?'} %>
<%= link_to book.name ,book_path(book.id)%>
</li>
<% end %>

</ul>

app/views/books/new.html.erb
<h1>新增書籍頁面</h1>

<% if @book.errors.any?%>
<ul>
<% @book.errors.full_messages.each do |message|%>
<li><%= message %></li>
<% end %>
</ul>
<% end %>



<%= form_for(@book) do |f| %>
<%= f.label '書籍名稱'%>
<%= f.text_field :name %>
<br>
<%= f.label '書籍價格'%>
<%= f.text_field :price %>
<br>
<%= f.submit '送出'%>
<% end %>

app/views/books/show.html.erb
<h1><%  @book.name  %></h1>
<p><%  @book.price  %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crud2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="notice">
  <%= notice %>
  </div>
    <%= yield %>
  </body>
</html>